//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp9.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\02.DataLogFile_31.10.2022.xlsx")]
        public string txt_logfile {
            get {
                return ((string)(this["txt_logfile"]));
            }
            set {
                this["txt_logfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST10_FlowVolume.xlsm")]
        public string txt_st10_flowVolume {
            get {
                return ((string)(this["txt_st10_flowVolume"]));
            }
            set {
                this["txt_st10_flowVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST10_WeldingDistance.xlsm")]
        public string txt_st10_weldingDistance {
            get {
                return ((string)(this["txt_st10_weldingDistance"]));
            }
            set {
                this["txt_st10_weldingDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST40_Point_1.xlsm")]
        public string txt_st40_point1 {
            get {
                return ((string)(this["txt_st40_point1"]));
            }
            set {
                this["txt_st40_point1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST40_Point_2.xlsm")]
        public string txt_st40_point2 {
            get {
                return ((string)(this["txt_st40_point2"]));
            }
            set {
                this["txt_st40_point2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST40_Point_3.xlsm")]
        public string txt_st40_point3 {
            get {
                return ((string)(this["txt_st40_point3"]));
            }
            set {
                this["txt_st40_point3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST40_Point_4.xlsm")]
        public string txt_st40_point4 {
            get {
                return ((string)(this["txt_st40_point4"]));
            }
            set {
                this["txt_st40_point4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST40_Point_5.xlsm")]
        public string txt_st40_point5 {
            get {
                return ((string)(this["txt_st40_point5"]));
            }
            set {
                this["txt_st40_point5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST40_Point_6.xlsm")]
        public string txt_st40_point6 {
            get {
                return ((string)(this["txt_st40_point6"]));
            }
            set {
                this["txt_st40_point6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST60_Welding_Distance.xlsm")]
        public string txt_st60_welding_distance {
            get {
                return ((string)(this["txt_st60_welding_distance"]));
            }
            set {
                this["txt_st60_welding_distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST70_Plug_Force.xlsm")]
        public string txt_st70_plug_force {
            get {
                return ((string)(this["txt_st70_plug_force"]));
            }
            set {
                this["txt_st70_plug_force"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST80_Insulation_Resistance_HV.xlsm")]
        public string txt_st80_insulation_resistance_hv {
            get {
                return ((string)(this["txt_st80_insulation_resistance_hv"]));
            }
            set {
                this["txt_st80_insulation_resistance_hv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AVX2:AVX51")]
        public string st10FlowVolumeRange {
            get {
                return ((string)(this["st10FlowVolumeRange"]));
            }
            set {
                this["st10FlowVolumeRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUM2:AUM51")]
        public string st10WeldingDistanceRange {
            get {
                return ((string)(this["st10WeldingDistanceRange"]));
            }
            set {
                this["st10WeldingDistanceRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BJI2:BJI51")]
        public string st40_point1_Range {
            get {
                return ((string)(this["st40_point1_Range"]));
            }
            set {
                this["st40_point1_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BJP2:BJP51")]
        public string st40_point2_Range {
            get {
                return ((string)(this["st40_point2_Range"]));
            }
            set {
                this["st40_point2_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BJW2:BJW51")]
        public string st40_point3_Range {
            get {
                return ((string)(this["st40_point3_Range"]));
            }
            set {
                this["st40_point3_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BKD2:BKD51")]
        public string st40_point4_Range {
            get {
                return ((string)(this["st40_point4_Range"]));
            }
            set {
                this["st40_point4_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BKK2:BKK51")]
        public string st40_point5_Range {
            get {
                return ((string)(this["st40_point5_Range"]));
            }
            set {
                this["st40_point5_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BKR2:BKR51")]
        public string st40_point6_Range {
            get {
                return ((string)(this["st40_point6_Range"]));
            }
            set {
                this["st40_point6_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BPU2:BPU51")]
        public string st60_welding_distance_Range {
            get {
                return ((string)(this["st60_welding_distance_Range"]));
            }
            set {
                this["st60_welding_distance_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BDV2:BDV51")]
        public string st70_plug_force_Range {
            get {
                return ((string)(this["st70_plug_force_Range"]));
            }
            set {
                this["st70_plug_force_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BAA2:BAA51")]
        public string st80_insulation_resistance_hv_Range {
            get {
                return ((string)(this["st80_insulation_resistance_hv_Range"]));
            }
            set {
                this["st80_insulation_resistance_hv_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST80_Leak_Test.xlsm")]
        public string txt_st80_leak_test {
            get {
                return ((string)(this["txt_st80_leak_test"]));
            }
            set {
                this["txt_st80_leak_test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AXA2:AXA51")]
        public string st80_leak_test_Range {
            get {
                return ((string)(this["st80_leak_test_Range"]));
            }
            set {
                this["st80_leak_test_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST80_Resistivity_CP.xlsm")]
        public string txt_st80_resistivity_cp {
            get {
                return ((string)(this["txt_st80_resistivity_cp"]));
            }
            set {
                this["txt_st80_resistivity_cp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AYK2:AYK51")]
        public string st80_resistivity_cp_Range {
            get {
                return ((string)(this["st80_resistivity_cp_Range"]));
            }
            set {
                this["st80_resistivity_cp_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST80_Resistivity_PE_to_CP.xlsm")]
        public string txt_st80_resistivity_pe_to_cp {
            get {
                return ((string)(this["txt_st80_resistivity_pe_to_cp"]));
            }
            set {
                this["txt_st80_resistivity_pe_to_cp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AYD2:AYD51")]
        public string st80_resistivity_pe_to_cp_Range {
            get {
                return ((string)(this["st80_resistivity_pe_to_cp_Range"]));
            }
            set {
                this["st80_resistivity_pe_to_cp_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST80_Resistivity_PP.xlsm")]
        public string txt_st80_resistivity_pp {
            get {
                return ((string)(this["txt_st80_resistivity_pp"]));
            }
            set {
                this["txt_st80_resistivity_pp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AYR2:AYR51")]
        public string st80_resistivity_pp_Range {
            get {
                return ((string)(this["st80_resistivity_pp_Range"]));
            }
            set {
                this["st80_resistivity_pp_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST80_Temperature_DC_minus.xlsm")]
        public string txt_st80_temperature_dc_minus {
            get {
                return ((string)(this["txt_st80_temperature_dc_minus"]));
            }
            set {
                this["txt_st80_temperature_dc_minus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AYY2:AYY51")]
        public string st80_temperature_dc_minus_Range {
            get {
                return ((string)(this["st80_temperature_dc_minus_Range"]));
            }
            set {
                this["st80_temperature_dc_minus_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST80_Temperature_DC_plus.xlsm")]
        public string txt_st80_temperature_dc_plus {
            get {
                return ((string)(this["txt_st80_temperature_dc_plus"]));
            }
            set {
                this["txt_st80_temperature_dc_plus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AZF2:AZF51")]
        public string st80_temperature_dc_plus_Range {
            get {
                return ((string)(this["st80_temperature_dc_plus_Range"]));
            }
            set {
                this["st80_temperature_dc_plus_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST90_Pin_Length_1.xlsm")]
        public string txt_st90_pin_length_1 {
            get {
                return ((string)(this["txt_st90_pin_length_1"]));
            }
            set {
                this["txt_st90_pin_length_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BEN2:BEN51")]
        public string st90_pin_length_1_Range {
            get {
                return ((string)(this["st90_pin_length_1_Range"]));
            }
            set {
                this["st90_pin_length_1_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST90_Pin_Length_2.xlsm")]
        public string txt_st90_pin_length_2 {
            get {
                return ((string)(this["txt_st90_pin_length_2"]));
            }
            set {
                this["txt_st90_pin_length_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BEU2:BEU51")]
        public string st90_pin_length_2_Range {
            get {
                return ((string)(this["st90_pin_length_2_Range"]));
            }
            set {
                this["st90_pin_length_2_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST90_Pin_Length_3.xlsm")]
        public string txt_st90_pin_length_3 {
            get {
                return ((string)(this["txt_st90_pin_length_3"]));
            }
            set {
                this["txt_st90_pin_length_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BFB2:BFB51")]
        public string st90_pin_length_3_Range {
            get {
                return ((string)(this["st90_pin_length_3_Range"]));
            }
            set {
                this["st90_pin_length_3_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST90_Pin_Length_5.xlsm")]
        public string txt_st90_pin_length_5 {
            get {
                return ((string)(this["txt_st90_pin_length_5"]));
            }
            set {
                this["txt_st90_pin_length_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BFP2:BFP51")]
        public string st90_pin_length_5_Range {
            get {
                return ((string)(this["st90_pin_length_5_Range"]));
            }
            set {
                this["st90_pin_length_5_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST90_Pin_Length_6.xlsm")]
        public string txt_st90_pin_length_6 {
            get {
                return ((string)(this["txt_st90_pin_length_6"]));
            }
            set {
                this["txt_st90_pin_length_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BFW2:BFW51")]
        public string st90_pin_length_6_Range {
            get {
                return ((string)(this["st90_pin_length_6_Range"]));
            }
            set {
                this["st90_pin_length_6_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST90_Pin_Length_7.xlsm")]
        public string txt_st90_pin_length_7 {
            get {
                return ((string)(this["txt_st90_pin_length_7"]));
            }
            set {
                this["txt_st90_pin_length_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BGD2:BGD51")]
        public string st90_pin_length_7_Range {
            get {
                return ((string)(this["st90_pin_length_7_Range"]));
            }
            set {
                this["st90_pin_length_7_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\MFU_ST90_Pin_Length_8.xlsm")]
        public string txt_st90_pin_length_8 {
            get {
                return ((string)(this["txt_st90_pin_length_8"]));
            }
            set {
                this["txt_st90_pin_length_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BGK2:BGK51")]
        public string st90_pin_length_8_Range {
            get {
                return ((string)(this["st90_pin_length_8_Range"]));
            }
            set {
                this["st90_pin_length_8_Range"] = value;
            }
        }
    }
}
